intel_oneAPI:
	ifort pi_integral_coarray.f -o pi_integral_coarray -coarray -lintlc 
	
intel:
	/opt/intel/bin/ifort pi_integral_coarray.f -o pi_integral_coarray -coarray -lintlc -Wl,-rpath,/opt/intel/lib/intel64 -L/opt/intel/lib/intel64 
	
