gnu:
	/home/leo/OpenCoarrays/prerequisites/builds/opencoarrays/2.9.2/bin/caf -g -O0 -fbacktrace -Wall hello_world_coarray.f -o hello_world_coarray 
# baixando e compilando no meu home os compiladores GNU em:
# https://github.com/sourceryinstitute/OpenCoarrays
