gnu:
	caf -g -O0 -fbacktrace -Wall hello_world_coarray.f -o hello_world_coarray 
# baixando e compilando no meu home os compiladores GNU em:
# https://github.com/sourceryinstitute/OpenCoarrays
# ou usando o Homebrew (linuxbrex), que já baixa os binários!

run:
	cafrun -np 6 ./hello_world_coarray
