all:
	/opt/intel/bin/ifort hello_world_coarray.f -o hello_world_coarray -lintlc -coarray -Wl,-rpath,/opt/intel/lib/intel64 -L/opt/intel/lib/intel64 
#	/opt/intel/bin/ifort hello_world_coarray.f -o hello_world_coarray -lintlc -coarray=distributed -coarray-num-images=5 -Wl,-rpath,/opt/intel/lib/intel64 -L/opt/intel/lib/intel64 
	
